exports.seed = function(knex, Promise) {
  return knex.raw('delete from "posts"; alter sequence blog_id_seq restart with 3')
    .then(function () {
      const blogs = [{
        id: 1,
        title: "VAPE",
        body: 'Bacon ipsum dolor amet capicola hamburger frankfurter porchetta, short ribs cow meatball sirloin ribeye short loin cupim pork ham jerky chuck. Strip steak burgdoggen pork belly, capicola ribeye swine tongue filet mignon porchetta. Kevin prosciutto chicken landjaeger jerky. Meatloaf pork belly filet mignon t-bone. Fatback beef beef ribs shankle meatball. Shank picanha frankfurter doner, shoulder kevin landjaeger pork chop swine turducken ribeye ground round venison fatback. Jerky frankfurter sausage picanha prosciutto pancetta ground round salami venison turducken kevin corned beef pork loin ham. Boudin brisket pork chop, corned beef ground round andouille porchetta pancetta swine beef ribs capicola. Filet mignon brisket ground round, sirloin capicola tri-tip boudin bacon shank ribeye drumstick tail shankle. Filet mignon picanha pork belly pancetta, spare ribs kielbasa boudin ham swine tongue jowl porchetta cupim. Hamburger doner bacon, chuck pastrami short ribs tongue landjaeger picanha venison boudin. Biltong burgdoggen pork loin hamburger chicken drumstick doner picanha.',
        author: 'Zac',
        image_url: 'https://vapemagazine.com/wp-content/uploads/2015/07/What-are-the-Dangers-of-Vaping.jpg'
      },{
        id: 2,
        title: "VAPE NASH",
        body: 'Spicy jalapeno bacon ipsum dolor amet prosciutto chuck shank, ball tip drumstick frankfurter swine cupim turducken. Frankfurter ball tip bacon, beef ribs spare ribs doner bresaola chicken biltong leberkas filet mignon pork chop pastrami. Boudin drumstick pastrami salami brisket meatball tail venison burgdoggen ball tip pig picanha meatloaf swine alcatra. Drumstick jerky kevin strip steak prosciutto pastrami. Strip steak t-bone hamburger, cupim burgdoggen chuck alcatra sirloin boudin meatloaf. Kielbasa biltong strip steak bresaola. Tail cow tongue flank fatback shoulder ball tip pork belly. Porchetta short loin tri-tip beef kevin pastrami bresaola. Pork belly tongue fatback picanha beef, spare ribs filet mignon bacon corned beef boudin. Strip steak t-bone sirloin ball tip pig chicken. Salami pig meatball flank porchetta chuck rump pastrami spare ribs pork jowl meatloaf drumstick ground round cupim. Rump shankle tail, bresaola bacon cupim pork belly pork loin kielbasa boudin flank burgdoggen biltong salami. Sirloin short ribs pork, pastrami fatback shank turkey landjaeger beef flank corned beef tenderloin boudin biltong ground round. Pastrami jerky kevin bacon. Boudin beef ribs tongue ham hock frankfurter, capicola jowl pastrami picanha landjaeger. Kevin capicola meatball shoulder t-bone venison sirloin. Tongue salami turkey, shoulder leberkas andouille bresaola. Pastrami fatback filet mignon, short loin burgdoggen beef pork chop turducken jowl pancetta kielbasa andouille chuck tenderloin t-bone. Burgdoggen venison shank tri-tip tail landjaeger. Shoulder cow shank t-bone strip steak corned beef picanha filet mignon turkey pork chop venison ball tip doner. Cupim tail turducken, landjaeger swine chuck tenderloin shank corned beef capicola pork tri-tip. Pancetta kielbasa brisket andouille leberkas pork loin, pastrami strip steak burgdoggen shank. Ground round brisket pork belly biltong tenderloin sirloin, meatloaf fatback burgdoggen. Swine meatloaf pancetta alcatra t-bone burgdoggen. Filet mignon jerky rump ham hock chicken, tenderloin pork chop bacon tail. Ground round hamburger filet mignon biltong sausage. Corned beef cupim salami t-bone, sirloin boudin ribeye cow pig chicken ham pork kevin. Turducken alcatra kielbasa tail, tenderloin shoulder tri-tip biltong kevin.',
        author: 'Matt',
        image_url: 'http://media.gq.com/photos/58ee3fad8d87a531f333af00/16:9/pass/vape-god.jpg'
      }]
      return knex('posts').insert(blogs);
    });
};
